### PR TITLE
AndroidX support

### LINKED ISSUE #205: Androidx support
Does this library support androidx ?

### PR DESCRIPTION
**Pull request by tank777**
Fixed #205

### CODE REVIEW

**Comment by jacobmattsson** [comment]
Please merge this PR and publish a new version with AndroidX support!

**Comment by tank777** [comment]
@mandybess  and @thoughtbot for the great library. I am updating  new version on fork repo  for AndroidX support. Let me know If it will create any licence issue or some other issue

Please check my fork repo https://github.com/tank777/expandable-recycler-view

## Download
```groovy
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
ExpandableRecyclerView:
```groovy
implementation 'com.github.tank777.expandable-recycler-view:expandablerecyclerview:1.6@aar'
```

ExpandableCheckRecyclerView:
```groovy
implementation 'com.github.tank777.expandable-recycler-view:expandablecheckrecyclerview:1.6@aar'
```

**Review by mike-burns — APPROVED** [review]
This idea makes sense. I haven't tried it yet but we should merge some form of this.

**Comment by bpappin** [comment]
is this PR still open? What version did this go into?

**Comment by mike-burns** [comment]
This PR is still open. I've been marking PRs as approved so we can fast-track those through and cut a new release.

**Comment by bpappin** [comment]
Why are these PRs sitting around?

**Comment by stefannibrasil** [comment]
Closing this as this library is deprecated: https://github.com/thoughtbot/expandable-recycler-view/pull/235

**Pull request closed without merging**
